#!/usr/bin/with-contenv bash

if ! [[ $ENABLE_INDIVIDUAL_REC -eq 1 || x$ENABLE_INDIVIDUAL_REC == xtrue ]]; then
    sleep infinity
fi

[[ -z $REC_PCAP_DIR ]] && echo 'FATAL ERROR: REC_PCAP_DIR must be set' && exit 1
[[ -z $INDIVIDUAL_REC_DIR ]] && echo 'FATAL ERROR: INDIVIDUAL_REC_DIR must be set' && exit 1


cd $REC_PCAP_DIR

while true; do
    # find pcap file with last modified time > 0.1 minutes, to ensure the pcap file is in finish state
    for PCAP_FILE in $(find *.pcap -mmin +0.1 2>/dev/null); do
        VIDEO_FILE=$(basename $PCAP_FILE .pcap).mkv

        echo "Converting $PCAP_FILE to $VIDEO_FILE"

        if gst-launch-1.0 filesrc location = $PCAP_FILE ! pcapparse ! \
                "application/x-rtp, media=video, clock-rate=90000, encoding-name=VP8-DRAFT-IETF-01" ! \
                rtpvp8depay ! matroskamux ! filesink location=$VIDEO_FILE >/dev/null; then
            rm -f $PCAP_FILE
            mv $VIDEO_FILE $INDIVIDUAL_REC_DIR/
        else
            mv $PCAP_FILE $PCAP_FILE.error
        fi
    done

    sleep 5
done
