version: '3.8'

services:
    # Auth Frontend
    vmfront:
        image: dpnm/vmfront:latest
        env_file: .env
        ports:
            - '3000:3000'
        networks:
            jitsi_meet:

    # Auth API Backend
    vmapi:
        image: dpnm/vmapi:latest
        env_file: .env
        ports:
            - '5000:5000'
        command: /vmeeting-api/wait-for-it.sh -t 0 mongo:27017 -- nodemon -x "node app.js || (sleep 10; touch app.js)"
        networks:
            jitsi_meet:

    mongo:
        image: dpnm/mongo:latest
        env_file: .env
        volumes:
            - ~/.jitsi-meet-cfg/mongo/db:/data/db
        # We use WiredTiger in all environments. In development environments we use small files
        # to conserve disk space, and disable the journal for a minor performance gain.
        # See https://docs.mongodb.com/v3.0/reference/program/mongod/#options for complete details.
        command: mongod --smallfiles --nojournal --storageEngine wiredTiger
        networks:
            jitsi_meet:
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"

    web:
        image: theun/web:latest
        env_file: .env
        volumes:
            - ~/.jitsi-meet-cfg/web:/config
            - ~/.jitsi-meet-cfg/web/letsencrypt:/etc/letsencrypt
            - ~/.jitsi-meet-cfg/transcripts:/usr/share/jitsi-meet/transcripts
        ports:
            - '80:80'
            - '443:443'
        networks:
            jitsi_meet:
                aliases:
                    - meet.jitsi
        deploy:
            placement:
                constraints:
                    - "node.role==manager"

    # XMPP server
    prosody:
        image: theun/prosody:latest
        env_file: .env
        networks:
            jitsi_meet:
                aliases:
                    - xmpp.meet.jitsi

    # Focus component
    jicofo:
        image: theun/jicofo:latest
        env_file: .env
        networks:
            jitsi_meet:

    # Video bridge
    jvb:
        image: dpnm/jvb:latest
        env_file: .env
        ports:
            - target: 10000
              published: 10000
              protocol: udp
              mode: host
            - target: 4443
              published: 4443
              protocol: tcp
              mode: host
        volumes:
            - /sys:/rootfs/sys:ro
            - /proc:/rootfs/proc:ro
            - /etc:/rootfs/etc:ro
        environment:
            - HOST_PROC=/rootfs/proc
            - HOST_SYS=/rootfs/sys
            - HOST_ETC=/rootfs/etc
        networks:
            jitsi_meet:
        deploy:
            # we need exactly one jvb for each host
            mode: global

    jibri:
        image: dpnm/jibri:latest
        env_file: .env
        environment:
            - DISPLAY=:0
        volumes:
            - /dev/shm:/dev/shm
        networks:
            jitsi_meet:
        deploy:
            replicas: 1

    # Monitoring stack
    influxdb:
        image: influxdb:1.8
        networks:
            jitsi_meet:

    grafana:
        image: dpnm/grafana:latest
        user: "1000"
        ports:
            - '3010:3000'
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
        networks:
            jitsi_meet:

networks:
    jitsi_meet:
        # ipam:
        #     driver: default
        #     config:
        #         - subnet: 172.28.0.0/16
