version: '3.8'

services:
    # Frontend
    web:
        image: jitsi/web:latest
        env_file: .env
        ports:
            - '80:80'
            - '443:443'
        networks:
            jitsi_meet:
                aliases:
                    - meet.jitsi
        deploy:
            placement:
                constraints:
                    - "node.role==manager"

    # XMPP server
    prosody:
        image: jitsi/prosody:latest
        env_file: .env
        networks:
            jitsi_meet:
                aliases:
                    - xmpp.meet.jitsi

    # Focus component
    jicofo:
        image: jitsi/jicofo:latest
        env_file: .env
        depends_on:
            - prosody
        networks:
            jitsi_meet:

    # Video bridge
    jvb:
        image: dpnm/jvb:latest
        env_file: .env

        ports:
            - target: 10000
              published: 10000
              protocol: udp
              mode: host
            - target: 4443
              published: 4443
              protocol: tcp
              mode: host
        volumes:
            # Telegraf
            - /sys:/rootfs/sys:ro
            - /proc:/rootfs/proc:ro
            - /etc:/rootfs/etc:ro
        environment:
            # Telegraf
            - HOST_PROC=/rootfs/proc
            - HOST_SYS=/rootfs/sys
            - HOST_ETC=/rootfs/etc
        depends_on:
            - prosody
        networks:
            jitsi_meet:
        deploy:
            # we need exactly one jvb for each host
            mode: global

    jibri:
        image: dpnm/jibri:latest
        env_file: .env
        environment:
            - DISPLAY=:0
        volumes:
            - /dev/shm:/dev/shm
        networks:
            jitsi_meet:
        deploy:
            replicas: 8
        depends_on:
            - jicofo

    # Monitoring stack
    influxdb:
        image: influxdb:1.8
        networks:
            jitsi_meet:

    grafana:
        image: dpnm/grafana:latest
        user: "1000"
        ports:
            - '3000:3000'
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
        depends_on:
            - influxdb
        networks:
            jitsi_meet:

networks:
    jitsi_meet:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
