version: '3.8'

services:
    influxdb:
        image: influxdb:1.8
        restart: ${RESTART_POLICY}
        expose:
            - '8086'
        ports:
            - '8083:8083'
        volumes:
            - ${CONFIG}/influxdb:/var/lib/influxdb:Z
        networks:
            meet.jitsi:

    grafana:
        image: grafana/grafana:7.0.3
        user: "1000"
        ports:
            - '3000:3000'
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
        volumes:
            - ./grafana/provisioning/datasources/telegraf.yaml:/etc/grafana/provisioning/datasources/telegraf.yaml:ro
        depends_on:
            - influxdb
        networks:
            meet.jitsi:

    chronograf:
        image: chronograf:1.8
        volumes:
            - ${CONFIG}/chronograf/data:/var/lib/chronograf:Z
        ports:
            - "8888:8888"
        depends_on:
            - influxdb
        networks:
            meet.jitsi:
