version: '3'

services:
    influxdb:
        image: influxdb:1.8
        restart: ${RESTART_POLICY}
        expose:
            - '8086'
        ports:
            - '8083:8083'
        volumes:
            - ${CONFIG}/influxdb:/var/lib/influxdb:Z
        networks:
            meet.jitsi:

    grafana:
        image: grafana/grafana:7.0.3
        user: "1000"
        ports:
            - '3000:3000'
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
        volumes:
            - ./grafana/provisioning/datasources/telegraf.yaml:/etc/grafana/provisioning/datasources/telegraf.yaml:ro
        depends_on:
            - influxdb
        networks:
            meet.jitsi:

    telegraf:
        # https://www.jacobtomlinson.co.uk/monitoring/2016/06/23/running-telegraf-inside-a-container
        image: telegraf:1.14
        restart: ${RESTART_POLICY}
        expose:
            - '8125'
            - '8092'
            - '8094'
        volumes:
            - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
            - /sys:/rootfs/sys:ro
            - /proc:/rootfs/proc:ro
            - /etc:/rootfs/etc:ro
        environment:
            - HOST_PROC=/rootfs/proc
            - HOST_SYS=/rootfs/sys
            - HOST_ETC=/rootfs/etc
        hostname: ${DOCKER_HOST_ADDRESS}
        depends_on:
            - influxdb
        networks:
            meet.jitsi:

    chronograf:
        image: chronograf:1.8
        volumes:
            - ${CONFIG}/chronograf/data:/var/lib/chronograf:Z
        ports:
            - "8888:8888"
        depends_on:
            - influxdb
        networks:
            meet.jitsi:
