#!/usr/bin/with-contenv bash
set -e
shopt -s nullglob

RECORDING_DIR=/recordings
UPLOAD_DIR=/uploads
WHITEBOARD_DIR=/files
BACKUP_DIR=/backup

[ ! -d "$INDIVIDUAL_REC_DIR" ] && echo "Directory ${INDIVIDUAL_REC_DIR} DOES NOT exists." && exit 1

if [ ! -z "$RECORDING_RETENTION_DAYS" ]; then
    while true; do
        # remove old recordings
        # cd $RECORDING_DIR && find * -mtime +${RECORDING_RETENTION_DAYS} -type f -exec rm {} \;
        # cd $RECORDING_DIR && find * -type d -empty -delete
        # cd $INDIVIDUAL_REC_DIR && find * -mtime +${RECORDING_RETENTION_DAYS} -type f -exec rm {} \;
        # cd $INDIVIDUAL_REC_DIR && find * -type d -empty -delete
        cd $UPLOAD_DIR && find * -mtime +${RECORDING_RETENTION_DAYS} -type f -exec rm {} \;
        cd $UPLOAD_DIR && find * -type d -empty -delete
        cd $WHITEBOARD_DIR && find * -mtime +${RECORDING_RETENTION_DAYS} -type f -exec rm {} \;
        cd $WHITEBOARD_DIR && find * -type d -empty -delete

        # backup mongodb
        DATE=$(date +"%Y-%m-%d")
        BACKUP_NAME="mongodb_backup_$DATE.gz"
        echo "Backing up mongodb : mongodump --username $VMEETING_DB_USER --password $VMEETING_DB_PASS VMEETING_DB_URL --gzip --archive=$BACKUP_DIR/$BACKUP_NAME"
        cd $BACKUP_DIR && mongodump --username $VMEETING_DB_USER --password $VMEETING_DB_PASS $VMEETING_DB_URL --gzip --archive=$BACKUP_DIR/$BACKUP_NAME

        # 7일 이상된 백업 삭제
        find $BACKUP_DIR -mtime +7 -type f -exec rm -f {} \;

        # check every 24h
        sleep 24h
    done
fi
