#!/usr/bin/with-contenv bash

JAVA_SYS_PROPS="-Dnet.java.sip.communicator.SC_HOME_DIR_LOCATION=/ -Dnet.java.sip.communicator.SC_HOME_DIR_NAME=config -Djava.util.logging.config.file=/config/logging.properties -Dconfig.file=/config/jvb.conf"

HOST_PUBLIC_IP=$(dig +short myip.opendns.com @resolver1.opendns.com)

if [[ ! -z "$HOST_PUBLIC_IP" ]]; then
    LOCAL_ADDRESS=$(ip route get "$HOST_PUBLIC_IP" | head -n1 | sed -n 's/.*src \([0-9.]\+\).*/\1/p')
    JAVA_SYS_PROPS="$JAVA_SYS_PROPS -Dorg.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=$LOCAL_ADDRESS -Dorg.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=$HOST_PUBLIC_IP -Dorg.ice4j.ice.harvest.BLOCKED_INTERFACES=bridge"
else
    echo "ERROR: can not detect HOST_PUBLIC_IP!"
fi

DAEMON=/usr/share/jitsi-videobridge/jvb.sh
DEFAULT_DAEMON_OPTS="none"

DAEMON_OPTS=${JVB_ENABLE_APIS:=$DEFAULT_DAEMON_OPTS}

exec s6-setuidgid jvb /bin/bash -c "JAVA_SYS_PROPS=\"$JAVA_SYS_PROPS\" exec $DAEMON --apis=${DAEMON_OPTS}"

