[meta]
  dir = "/var/lib/influxdb/meta"

[data]
  dir = "/var/lib/influxdb/data"
  engine = "tsm1"
  wal-dir = "/var/lib/influxdb/wal"
  query-log-enabled = true

[http]
  auth-enabled = true
  https-enabled = true
  log-enabled = true
  access-log-path = "/var/log/influxdb/access.log"
  https-certificate = "/etc/ssl/influxdb.crt"
  https-private-key = "/etc/ssl/influxdb.key"

[coodinator]
  log-queries-after = "0s"
