#!/usr/bin/with-contenv bash

# make our folders
mkdir -p \
    /config/{nginx/site-confs,keys} \
    /run \
    /var/lib/nginx/tmp/client_body \
    /var/tmp/nginx

# generate keys (maybe)
if [[ $DISABLE_HTTPS -ne 1 ]]; then
    if [[ $ENABLE_LETSENCRYPT -eq 1 ]]; then
        while [[ ! -f /etc/letsencrypt/live/$LETSENCRYPT_DOMAIN/fullchain.pem ]]; do
            sleep 15
        done
        echo "using keys found in /etc/letsencrypt/liv/$LETSENCRYPT_DOMAIN"
    else
        # use self-signed certs
        until [[ -f /config/keys/cert.key && -f /config/keys/cert.crt ]]; do
            echo "using keys found in /config/keys"
        done
    fi
fi

# copy config files
tpl /defaults/nginx.conf > /config/nginx/nginx.conf

if [[ ! -f /config/nginx/whiteboard.conf ]]; then
    tpl /defaults/whiteboard.conf > /config/nginx/whiteboard.conf
fi

if [[ ! -f /config/nginx/meet.conf ]]; then
    tpl /defaults/meet.$NODE_ENV.conf > /config/nginx/meet.conf
fi

if [[ ! -f /config/nginx/ssl.conf ]]; then
    tpl /defaults/ssl.conf > /config/nginx/ssl.conf
fi

if [[ ! -f /config/nginx/site-confs/default ]]; then
    tpl /defaults/default > /config/nginx/site-confs/default
fi
