#!/usr/bin/with-contenv bash

# make our folders
mkdir -p \
    /config/{nginx/site-confs,keys} \
    /run \
    /var/lib/nginx/tmp/client_body \
    /var/tmp/nginx

# generate keys (maybe)
if [[ $DISABLE_HTTPS -ne 1 ]]; then
    if [[ $ENABLE_LETSENCRYPT -eq 1 ]]; then
        mkdir -p /config/acme.sh
        pushd /opt
        sh ./acme.sh --install --home /config/acme.sh --accountemail $LETSENCRYPT_EMAIL
        popd

        if [[ $LETSENCRYPT_USE_STAGING -ne 1 || ! -f /config/acme-certs/$LETSENCRYPT_DOMAIN/fullchain.pem ]]; then
            export LE_WORKING_DIR="/config/acme.sh"
            # TODO: move away from standalone mode to webroot mode.
            /config/acme.sh/acme.sh \
                --issue \
                --standalone \
                --pre-hook "if [[ -d /var/run/s6/services/nginx ]]; then s6-svc -d /var/run/s6/services/nginx; fi" \
                --post-hook "if [[ -d /var/run/s6/services/nginx ]]; then s6-svc -u /var/run/s6/services/nginx; fi" \
                -d $LETSENCRYPT_DOMAIN
            rc=$?
            if [[ $rc -eq 1 ]]; then
                echo "Failed to obtain a certificate from the Let's Encrypt CA."
                # this tries to get the user's attention and to spare the
                # authority's rate limit:
                sleep 15
                echo "Exiting."
                exit 1
            fi
            if [[ $rc -eq 0 ]]; then
                mkdir -p /config/acme-certs/$LETSENCRYPT_DOMAIN
                if ! /config/acme.sh/acme.sh \
                        --install-cert -d $LETSENCRYPT_DOMAIN \
                        --key-file /config/acme-certs/$LETSENCRYPT_DOMAIN/key.pem \
                        --fullchain-file /config/acme-certs/$LETSENCRYPT_DOMAIN/fullchain.pem ; then
                    echo "Failed to install certificate."
                    # this tries to get the user's attention and to spare the
                    # authority's rate limit:
                    sleep 15
                    echo "Exiting."
                    exit 1
                fi
            fi
        fi
    else
        # use self-signed certs
        if [[ -f /config/keys/cert.key && -f /config/keys/cert.crt ]]; then
            echo "using keys found in /config/keys"
        else
            echo "generating self-signed keys in /config/keys, you can replace these with your own keys if required"
            SUBJECT="/C=US/ST=TX/L=Austin/O=jitsi.org/OU=Jitsi Server/CN=*"
            openssl req -new -x509 -days 3650 -nodes -out /config/keys/cert.crt -keyout /config/keys/cert.key -subj "$SUBJECT"
        fi
    fi
fi

# generate username/password for individual downloading
if [[ $ENABLE_INDIVIDUAL_REC -eq 1 || x$ENABLE_INDIVIDUAL_REC == xtrue ]]; then
    [ -z "$IND_REC_DOWNLOAD_USER" ] && echo "ENV IND_REC_DOWNLOAD_USER does NOT set." && exit 1
    [ -z "$IND_REC_DOWNLOAD_PASSWORD" ] && echo "ENV IND_REC_DOWNLOAD_PASSWORD does NOT set." && exit 1
    htpasswd -b -c /config/nginx/.htpasswd $IND_REC_DOWNLOAD_USER $IND_REC_DOWNLOAD_PASSWORD
fi
# copy config files
tpl /defaults/nginx.conf > /config/nginx/nginx.conf

if [[ ! -f /config/nginx/whiteboard.conf ]]; then
    tpl /defaults/whiteboard.conf > /config/nginx/whiteboard.conf
fi

if [[ ! -f /config/nginx/meet.conf ]]; then
    tpl /defaults/meet.$NODE_ENV.conf > /config/nginx/meet.conf
fi

if [[ ! -f /config/nginx/ssl.conf ]]; then
    tpl /defaults/ssl.conf > /config/nginx/ssl.conf
fi

if [[ ! -f /config/nginx/site-confs/default ]]; then
    tpl /defaults/default > /config/nginx/site-confs/default
fi

for config in /defaults/config*.js
do
    fname=${config##*/}
    if [[ ! -f /config/${fname} ]]; then
        cp /defaults/${fname} /config/${fname}
        sed -i \
            -e "s/muc.jitsi-meet.example.com/muc.<\!--# echo var=\"subdomain\" default=\"\" -->jitsi-meet.example.com/g" \
            /config/${fname}

        sed -i \
            -e "s#jitsi-meet.example.com#$XMPP_DOMAIN#g" \
            -e "s#bosh:.*#bosh: '${PUBLIC_URL}/http-bind',#" \
            -e "s#// focusUserJid:.*#focusUserJid: '${JICOFO_AUTH_USER}@${XMPP_AUTH_DOMAIN}',#" \
            /config/${fname}

        sed -i \
            -e "s#// startAudioMuted:.*#startAudioMuted: 20,#" \
            -e "s#// startVideoMuted:.*#startVideoMuted: 500,#" \
            /config/${fname}

        sed -i \
            -e "s#// requireDisplayName:.*#requireDisplayName: true,#" \
            /config/${fname}

        if [[ $ENABLE_XMPP_WEBSOCKET -eq 1 ]]; then
            if [[ -z "$PUBLIC_URL" ]]; then
                echo 'FATAL ERROR: If ENABLE_XMPP_WEBSOCKET is set to 1, PUBLIC_URL must be defined!'
                exit 1
            fi

            sed -i \
            -e "s#// websocket:.*#websocket: '${PUBLIC_URL/http/ws}/xmpp-websocket',#" \
            /config/${fname}
        fi

        if [[ $ENABLE_RECORDING -eq 1 || x$ENABLE_RECORDING == xtrue ]]; then
            sed -i \
                -e "/\/\/ Recording.*/a hiddenDomain: '$XMPP_RECORDER_DOMAIN'," \
                -e "s#// fileRecordingsEnabled:.*#fileRecordingsEnabled: true,#" \
                -e "s#// liveStreamingEnabled:.*#liveStreamingEnabled: true,#" \
            /config/${fname}
        fi

        if [[ $ENABLE_AUTH -eq 1 ]]; then
            if [[ $ENABLE_GUESTS -eq 1 ]]; then
                sed -i \
                    -e "s#// anonymousdomain:.*#anonymousdomain: '${XMPP_GUEST_DOMAIN}',#" \
                    /config/${fname}
            fi

            sed -i \
                -e "s#// authdomain:.*#authdomain: '${XMPP_DOMAIN}',#" \
                /config/${fname}
        fi

        if [[ -z "$(grep -om1 'whiteboard_base:' /config/${fname})" ]]; then
            if [[ ! -z "${WHITEBOARD_PUBLIC_URL}" ]]; then
                sed -i \
                    -e "/enableWelcomePage/a\    whiteboard_base: '${WHITEBOARD_PUBLIC_URL}'," \
                    /config/${fname}
            elif [[ ! -z "${WHITEBOARD_URL_BASE}" ]]; then
                sed -i \
                    -e "/enableWelcomePage/a\    whiteboard_base: '${PUBLIC_URL}/whiteboard/'," \
                    /config/${fname}
            fi
        fi

        if [[ $ENABLE_TRANSCRIPTIONS -eq 1 || "$ENABLE_TRANSCRIPTIONS" == "true" ]]; then
            sed -i \
                -e "s#// transcribingEnabled:.*#transcribingEnabled: true,#" \
                /config/${fname}
        fi

        # for new config, we can use the new method with tpl
        if [[ -f /defaults/custom-${fname} ]]; then
            tpl /defaults/custom-${fname} >> /config/${fname}
        fi
    fi
done

for interface_config in /defaults/interface_config*.js
do
    fname=${interface_config##*/}
    if [[ ! -f /config/${fname} ]]; then
        cp /defaults/${fname} /config/${fname}

        # It will remove parameter 'closedcaptions' from TOOLBAR_BUTTONS if ENABLE_TRANSCRIPTIONS is false,
        # because it enabled by default, but not supported out of the box.
        if [[ $ENABLE_TRANSCRIPTIONS -ne 1 && "$ENABLE_TRANSCRIPTIONS" != "true" ]]; then
            sed -i \
                -e "s#'closedcaptions', ##" \
                /config/${fname}
        fi

        if [[ $ENABLE_RECORDING -ne 1 && "$ENABLE_RECORDING" != "true" ]]; then
            sed -i \
                -e "s#'recording',##" \
                -e "s#'livestreaming',##" \
                /config/${fname}
        fi

    fi
done

if [[ ! -f /config/passni-config.json ]]; then
    cp /defaults/passni-config.json /config/passni-config.json
fi

if [[ ! -f /config/title.html ]]; then
    cp /defaults/title*.html /config/
fi
