#!/usr/bin/with-contenv bash
set -x

if [[ $JVB_USE_PRIVATE_NET -eq 1 || x$JVB_USE_PRIVATE_NET == xtrue ]]; then
    if [ ! -f "$HOST_ETC/hostip" ]; then
        echo "can not find hostip file in host /etc. Exit ..."
        exit 1
    fi
    export PUBLIC_ADDRESS=$(cat $HOST_ETC/hostip | head -n 1 |  sed 's/ //g')
else
    export PUBLIC_ADDRESS=$(dig +short myip.opendns.com @resolver1.opendns.com +tcp)
fi

export LOCAL_ADDRESS=$(ip route get "$PUBLIC_ADDRESS" | head -n1 | sed -n 's/.*src \([0-9.]\+\).*/\1/p')
export SWARM_ADDRESS=$(ip route | grep "${JITSI_MEET_SUBNET}" | sed -n 's/.*src \([0-9.]\+\).*/\1/p')

if [[ -z $JVB_AUTH_PASSWORD ]]; then
    echo 'FATAL ERROR: JVB auth password must be set'
    exit 1
fi

OLD_JVB_AUTH_PASSWORD=passw0rd
if [[ "$JVB_AUTH_PASSWORD" == "$OLD_JVB_AUTH_PASSWORD" ]]; then
    echo 'FATAL ERROR: JVB auth password must be changed, check the README'
    exit 1
fi

if [[ ! -z $JVB_MAX_MEMORY ]]; then
    sed -i \
        -e "s/# VIDEOBRIDGE_MAX_MEMORY.*/VIDEOBRIDGE_MAX_MEMORY=${JVB_MAX_MEMORY}/g" \
        /usr/share/jitsi-videobridge/lib/videobridge.rc
fi

chown -R jvb:jitsi /config

# ssh key to connect to storage
if [[ -z $ID_RSA_BASE64 ]]; then
    echo 'FATAL ERROR: ID_RSA_BASE64 must be set'
    exit 1
fi

if [[ -z $ID_RSA_PUB_BASE64 ]]; then
    echo 'FATAL ERROR: ID_RSA_PUB_BASE64 must be set'
    exit 1
fi

mkdir -p /root/.ssh/
echo $ID_RSA_BASE64 | openssl base64 -A -d | tee /root/.ssh/id_rsa
echo $ID_RSA_PUB_BASE64 | openssl base64 -A -d | tee /root/.ssh/id_rsa.pub

chmod 600 /root/.ssh/id_rsa
chmod 600 /root/.ssh/id_rsa.pub
chmod 644 /etc/ssh/ssh_config

mkdir -p $JVB_VIDEO_PCAP_DIR
chown -R jvb $JVB_VIDEO_PCAP_DIR


tpl /defaults/sip-communicator.properties > /config/sip-communicator.properties
if [[ -f /config/custom-sip-communicator.properties ]]; then
    cat /config/custom-sip-communicator.properties >> /config/sip-communicator.properties
fi

tpl /defaults/jvb.conf > /config/jvb.conf

if [[ ! -f /config/logging.properties ]]; then
    cp /defaults/logging.properties /config
fi
