#!/usr/bin/with-contenv bash

export LOCAL_ADDRESS=$(ip route | grep '172.28.0.0/16' | sed -n 's/.*src \([0-9.]\+\).*/\1/p')

if [[ -z $JVB_AUTH_PASSWORD ]]; then
    echo 'FATAL ERROR: JVB auth password must be set'
    exit 1
fi

OLD_JVB_AUTH_PASSWORD=passw0rd
if [[ "$JVB_AUTH_PASSWORD" == "$OLD_JVB_AUTH_PASSWORD" ]]; then
    echo 'FATAL ERROR: JVB auth password must be changed, check the README'
    exit 1
fi

if [[ ! -z $JVB_MAX_MEMORY ]]; then
    sed -i \
        -e "s/# VIDEOBRIDGE_MAX_MEMORY.*/VIDEOBRIDGE_MAX_MEMORY=${JVB_MAX_MEMORY}/g" \
        /usr/share/jitsi-videobridge/lib/videobridge.rc
fi

tpl /defaults/sip-communicator.properties > /config/sip-communicator.properties
if [[ -f /config/custom-sip-communicator.properties ]]; then
    cat /config/custom-sip-communicator.properties >> /config/sip-communicator.properties
fi

tpl /defaults/jvb.conf > /config/jvb.conf

if [[ ! -f /config/logging.properties ]]; then
    cp /defaults/logging.properties /config
fi

CONFIG="/etc/jitsi/videobridge/config"
HOCON_CONFIG="/config/jvb.conf"

if [ ! -f $HOCON_CONFIG ]; then
    echo "Generating an empty hocon config"
    echo "videobridge {
    http-servers {
        public {
            port = 9090
        }
    }
    websockets {
        enabled = true
        domain = \"$XMPP_DOMAIN:443\"
        tls = true
    }
}" >> $HOCON_CONFIG
fi

chown -R jvb:jitsi /config
