#!/usr/bin/with-contenv bash

if [[ -z $JVB_AUTH_PASSWORD ]]; then
    echo 'FATAL ERROR: JVB auth password must be set'
    exit 1
fi

OLD_JVB_AUTH_PASSWORD=passw0rd
if [[ "$JVB_AUTH_PASSWORD" == "$OLD_JVB_AUTH_PASSWORD" ]]; then
    echo 'FATAL ERROR: JVB auth password must be changed, check the README'
    exit 1
fi

if [[ ! -z $JVB_MAX_MEMORY ]]; then
    sed -i \
        -e "s/# VIDEOBRIDGE_MAX_MEMORY.*/VIDEOBRIDGE_MAX_MEMORY=${JVB_MAX_MEMORY}/g" \
        /usr/share/jitsi-videobridge/lib/videobridge.rc
fi

if [[ ! -f /config/sip-communicator.properties ]]; then
    tpl /defaults/sip-communicator.properties > /config/sip-communicator.properties
fi

LOCAL_ADDRESS=$(ip route | grep '172.28.0.0/16' | sed -n 's/.*src \([0-9.]\+\).*/\1/p')
sed -i \
        -e "s/org.jitsi.videobridge.rest.COLIBRI_WS_SERVER_ID=.*/org.jitsi.videobridge.rest.COLIBRI_WS_SERVER_ID=${LOCAL_ADDRESS}/" \
        /config/sip-communicator.properties


if [[ ! -f /config/logging.properties ]]; then
    cp /defaults/logging.properties /config
fi

CONFIG="/etc/jitsi/videobridge/config"
HOCON_CONFIG="/config/jvb.conf"
if ! grep -q "\-Dconfig.file" "$CONFIG"; then
    sed -i 's|JAVA_SYS_PROPS="|JAVA_SYS_PROPS="-Dconfig.file='"$HOCON_CONFIG"' |g' $CONFIG
fi

if [ ! -f $HOCON_CONFIG ]; then
    echo "Generating an empty hocon config"
    echo "videobridge {
    http-servers {
        public {
            port = 9090
        }
    }
    websockets {
        enabled = true
        domain = \"$XMPP_DOMAIN:443\"
        tls = true
    }
}" >> $HOCON_CONFIG
fi

chown -R jvb:jitsi /config
