# STT gateway API
location ~ ^/stt-gateway/ws {
    rewrite ^/stt-gateway/(.*)$ /$1 break;
    proxy_pass http://stt-gateway:18080;

    # WebSocket 헤더 처리
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;

    # 프록시 시간 초과 설정 (필요시 조정 가능)
    proxy_read_timeout 86400;
    proxy_send_timeout 86400;

    proxy_buffer_size 128k;
    proxy_buffer 32 128k;
}

location ~ ^/stt-gateway/api {
    rewrite ^/stt-gateway/api/(.*)$ /$1 break;
    proxy_pass http://stt-gateway:18080;
}

# medcmd ctrl fe
location ~ ^/medcmd/ctrl {
    proxy_pass http://medcmd-center-ctrl-front:13000;

    # 필요한 헤더 설정
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
