{
 "title": "Vmeeting",
 "description": "Performance metrics of Vmeeting cluster",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "jitsi_host",
    "label": "Vmeeting Servers",
    "query": "select DISTINCT(\"host\") from (select \"host\",last(\"conferences\") from \"jitsi_stats\" where $timeFilter group by \"host\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Conferences running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "jitsi_stats",
     "query": "SELECT sum(\"confs\") FROM (SELECT last(\"conferences\") AS \"confs\" FROM \"jitsi_stats\" WHERE $timeFilter GROUP BY \"host\")",
     "select": [
      [
       { "params": [ "conferences" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "!~", "value": "/./" }
     ]
    }
   ]
  },
  {
   "title": "Largest Conference",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "jitsi_stats",
     "query": "SELECT last(\"largest_conference\") FROM \"jitsi_stats\" WHERE (\"host\" !~ /./) AND $timeFilter",
     "select": [
      [
       { "params": [ "largest_conference" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "!~", "value": "/./" }
     ]
    }
   ]
  },
  {
   "title": "Total Participants",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "jitsi_stats",
     "query": "SELECT sum(\"x\") FROM (SELECT last(\"participants\") AS \"x\" FROM \"jitsi_stats\" WHERE $timeFilter GROUP BY \"host\")",
     "select": [
      [
       { "params": [ "participants" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "!~", "value": "/./" }
     ]
    }
   ]
  },
  {
   "title": "Video Channels",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT sum(\"x\") FROM (SELECT last(\"endpoints_sending_video\") AS \"x\" FROM \"jitsi_stats\" WHERE $timeFilter GROUP BY \"host\")",
     "select": [
      [
       { "params": [ "videochannels" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Audio channels",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT sum(\"x\") FROM (SELECT last(\"endpoints_sending_audio\") AS \"x\" FROM \"jitsi_stats\" WHERE $timeFilter GROUP BY \"host\")",
     "select": [
      [
       { "params": [ "endpoints_sending_audio" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Recordings",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "jitsi_stats",
     "select": [
      [
       { "params": [ "recording_active" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "!~", "value": "/./" }
     ]
    }
   ]
  },
  {
   "title": "Live streams",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "jitsi_stats",
     "select": [
      [
       { "params": [ "live_streaming_active" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "!~", "value": "/./" }
     ]
    }
   ]
  },
  {
   "title": "Jibri remain",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "jitsi_stats",
     "select": [
      [
       { "params": [ "jibri_detector_available" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "!~", "value": "/./" }
     ]
    }
   ]
  },
  {
   "title": "CPU: ${jitsi_host}",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "repeat": "jitsi_host",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "CPU",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "cpu",
     "query": "SELECT last(\"usage_user\") FROM \"cpu\" WHERE (\"host\" =~ /^$jitsi_host$/) AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$jitsi_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory: $jitsi_host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "repeat": "jitsi_host",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "total_memory",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "mem",
     "query": "SELECT last(\"total\") FROM \"mem\" WHERE (\"host\" =~ /^$jitsi_host$/) AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$jitsi_host$/" }
     ]
    },
    {
     "alias": "used_memory",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$jitsi_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Bitrate: $jitsi_host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "repeat": "jitsi_host",
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "alias": "server incoming",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "jitsi_stats",
     "select": [
      [
       { "params": [ "bit_rate_download" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$jitsi_host$/" }
     ]
    },
    {
     "alias": "server outgoing",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "jitsi_stats",
     "select": [
      [
       { "params": [ "bit_rate_upload" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$jitsi_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Loss Rate: $jitsi_host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "repeat": "jitsi_host",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "loss_rate_download",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "jitsi_stats",
     "select": [
      [
       { "params": [ "loss_rate_download" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$jitsi_host$/" }
     ]
    },
    {
     "alias": "loss_rate_upload",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "jitsi_stats",
     "select": [
      [
       { "params": [ "loss_rate_upload" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$jitsi_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Participants: $jitsi_host",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "repeat": "jitsi_host",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "participants",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT \"participants\" FROM \"jitsi_stats\" WHERE (\"host\" =~ /^$jitsi_host$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "participants" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$jitsi_host$/" }
     ]
    }
   ]
  }
 ]
}