#!/usr/bin/with-contenv bash
set -x

if [[ -z $JVB_VIDEO_PCAP_DIR ]]; then
    echo 'FATAL ERROR: JVB_VIDEO_PCAP_DIR must be set'
    exit 1
fi

cd $JVB_VIDEO_PCAP_DIR

while true; do
    for PCAP_FILE in $(find *.pcap 2>/dev/null); do
        VIDEO_FILE=$(basename $PCAP_FILE .pcap).mp4

        # video conversion is a cpu intensive task but does not need to be realtime,
        # thus set it to be nice
        if nice -n 15 gst-launch-1.0 filesrc location = $PCAP_FILE ! pcapparse ! \
                "application/x-rtp, media=video, clock-rate=90000, encoding-name=VP8-DRAFT-IETF-01" ! \
                rtpvp8depay ! vp8dec ! videoconvert ! x264enc pass=qual quantizer=23 ! mp4mux ! \
                filesink location=$VIDEO_FILE; then
            rsync $VIDEO_FILE root@storage:${INDIVIDUAL_REC_DIR}/
            rm -f $PCAP_FILE $VIDEO_FILE
        else
            mv $PCAP_FILE $PCAP_FILE.error
        fi

        sleep 1
    done

    sleep 10
done
