FROM node:12

RUN apt-get update && apt-get install -y vim inotify-tools curl make

# `/app/node_modules/.bin`을 $PATH 에 추가
ENV PATH /web/jitsi-meet/node_modules/.bin:$PATH

COPY lib-jitsi-meet/ /web/lib-jitsi-meet/
RUN cd /web/lib-jitsi-meet/ && npm install

WORKDIR /web/jitsi-meet

COPY jitsi-meet/ /web/jitsi-meet/
RUN cd /web/jitsi-meet/ && npm install && make dev
